name: Build
on:
  pull_request:
    branches:
      - dummy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af # コミットハッシュを指定
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::{AWS_ACCOUNT_ID}:role/{ROLE_NAME}
          role-session-name: MySessionName
      - run: aws sts get-caller-identity